---
driver:
  name: digitalocean
  digitalocean_client_id: <%= ENV['DIGITALOCEAN_CLIENT_ID'] %>
  digitalocean_api_key: <%= ENV['DIGITALOCEAN_API_KEY'] %>
  ssh_key: <%= Hipache::Helpers.private_key_file %>
  ssh_key_ids: <%= Hipache::Helpers.ssh_key_ids %>
suites:
  - name: default
    run_list:
      - recipe[webhook]
    attributes:
    excludes: ['macosx-10.9']
  - name: cli
    run_list:
      - recipe[webhook::cli]
    attributes:
    excludes: ['macosx-10.9']
