---
driver:
  name: digitalocean

platforms:
  - name: ubuntu-14-04-x64
  - name: ubuntu-12-04-x64
  - name: centos-7-0-x64
  - name: centos-6-5-x64

suites:
  - name: cli
    run_list:
      - recipe[webhook::cli]
    attributes:
