---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: centos-7.1
  - name: centos-6.7
  - name: macosx-10.10
    driver:
      box: roboticcheese/macosx-10.10
      ssh:
        insert_key: false
# - name: windows-2012

suites:
  - name: cli
    run_list:
      - recipe[webhook::cli]
    attributes:
    excludes:
      - macosx-10.10
  - name: app
    run_list:
      - recipe[webhook::app]
    attributes:
    excludes:
      - ubuntu-14.04
      - ubuntu-12.04
      - centos-7.1
      - centos-6.7
